# .gitlab-ci.yml file to be placed in the root of your repository

pages: # the job must be named pages
  image: node:latest
  stage: deploy
  script:
    - npm i -g pnpm
    - pnpm i --shamefully-flatten -f
    - pnpm run build
    - mv public public-vue # GitLab Pages hooks on the public folder
    - mv cordova/www public # rename the dist folder (result of npm run build)
  artifacts:
    paths:
      - public # artifact path must be /public for GitLab Pages to pick it up
  only:
    - master
