image: node:latest

stages:
  - setup
  - build
  - production

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    # Install deps
    - npm i -g @quasar/cli sails --offline
    - cd ./client && npm i && cd ..
    - cd ./panel && npm i && quasar build spa && cd ..
    - cd ./server && npm i && cd ..
  only:
    - master

setup:
  stage: setup
  script:
    # build the admin panel
    - cd ./client && npm i && cd ..
    - cd ./server && npm i && cd ..
    - cd ./client && npm run build && cd ..
  only:
    - master

# HEROKU
production:
  type: deploy
  stage: production
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=thepentecost --api-key=$HEROKU_API_KEY
  only:
    - master
