image: node:latest

stages:
  - setup
  - build
  - production

setup:
  stage: setup
  script:
    - npm i -g sails pnpm
  only:
    - master

build:
  stage: build
  script:
    - cd ./client && npm run build && cd ..
    - rm -R -v ./server/dist
    - mkdir -p ./server/dist
    - cp -f -R ./client/dist ./server
  artifacts:
    paths:
      - dist
  only:
    - master

# HEROKU
production:
  type: deploy
  stage: production
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=node-heroku-dpl --api-key=$HEROKU_API_KEY
  only:
    - master
