image: node:latest

stages:
  - setup
  - production

cache:
  paths:
    - node_modules/

setup:
  stage: setup
  script:
    - cd ./client && npm i && cd ..
    - cd ./server && npm i && cd ..
    - cd ./client && npm run build && cd ..
  only:
    - master

# HEROKU
production:
  type: deploy
  stage: production
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=node-heroku-dpl --api-key=$HEROKU_API_KEY
  only:
    - master
