image: node:latest

stages:
  - setup

cache:
  paths:
    - node_modules/

# HEROKU
production:
  type: deploy
  stage: production
  image: ruby:latest
  script:
    - cd ./client && npm i && cd ..
    - cd ./server && npm i && cd ..
    - cd ./client && npm run build && cd ..
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=pentecust --api-key=$HEROKU_API_KEY
  only:
    - master
