image: node:latest

stages:
  - setup
  - build
  - production

cache:
  paths:
    - node_modules/

setup:
  stage: setup
  script:
    - npm i -g sails pnpm
    - cd ./client && pnpm i --shamefully-flatten -f && cd ..
    - cd ./server && pnpm i && cd ..
  only:
    - master

build:
  stage: build
  script:
    - cd ./client && npm run build && cd ..
    - rm -R ./server/dist && cd ..
    - mkdir -p ./server/dist && cd ..
    - cp -f -R ./client/dist ./server && echo "done()" && cd ..
  artifacts:
    paths:
      - dist
  only:
    - master

# HEROKU
production:
  type: deploy
  stage: production
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=node-heroku-dpl --api-key=$HEROKU_API_KEY
  only:
    - master
