<template>
  <div>
    <v-container
      align-baseline
      align-center
      align-content-center
      align-content-end
      align-content-space-around
      align-content-space-between
      align-content-start
      align-end
      align-start
      d-flex
      fill-height
      fluid
      grid-list-xs
      id="id"
      justify-center
      justify-end
      justify-space-around
      justify-space-between
      justify-start
      reverse
      tag="div"
      wrap
    >
      <router-view></router-view>
    </v-container>
  </div>
</template>